### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by VerstreuteSeele** [H0QLCoder/Discord-Octo-Nuker#6]
Being a skid really has to be a painful job, scouring the internet all day long for amazing ideas to copy-paste, compile after adding shady code to it, and claiming it's yours. 

BTW, you cant distribute it as you were using a cracked version of the compiler lol.

Also, do you want me to attach decompiled versions of all your exes on the issues I'm gonna make on your repos so nobody uses your shit?

And don't even think about deleting this issue, as you did with the other 5. I got all day to write a bot that opens new ones

**Comment by H0QLCoder** [comment]
Go at please go I don't care for these comments

**Comment by H0QLCoder** [comment]
"Hazard" you happy

**Comment by H0QLCoder** [comment]
Second of all talking about deleting this issue as you did with other 5 ?

**Comment by H0QLCoder** [comment]
I did not close 5 others

**Comment by H0QLCoder** [comment]
just so you feel better I will make my own so I don't have to stand with people like you

**Comment by H0QLCoder** [comment]
I may not be the best at nuke's but I'm good at ddos

**Comment by H0QLCoder** [comment]
https://github.com/H0QLCoder/Octo-Hiter

**Comment by H0QLCoder** [comment]
Don't try me on this

**Comment by VerstreuteSeele** [comment]
You did delete 5 issues as this wouldnt be #6 otherwise

and you also wouldnt get defensive if i wouldnt be correct. simple psychology

**Comment by VerstreuteSeele** [comment]
feel free to hit my site with your skidded crap btw.

**Comment by VerstreuteSeele** [comment]
> > feel free to hit my site with your skidded crap btw.
> 
> You mean ping your site?

ayy. wassup galaxzy. ye lmao. he can do that. ping of death & slowloris be like

**Comment by H0QLCoder** [comment]
Kid has CLOUDFLARENET

**Comment by VerstreuteSeele** [comment]
"Kid", sorry to inform you that I am an adult and member of a group of security researchers & penetration testers. 

" has cloudflare" - so? Bypasses exist and can be done in under 20 lines of pure php. I'm sure you would be able to do that as you are totally not skidding code

**Comment by VerstreuteSeele** [comment]
Your lack of recognition for any of the other messages detailing your amusing failure and showing your lies, is quite hilarious by the way

**Comment by VerstreuteSeele** [comment]
Either way, you have proving yourself worthy a place in the hall of shame. That was quite literally all I was trying to do here. and the best part is I got paid for it. 

I highly appreciate your time and wish you best of luck for your future career

- CC | CynthiaLabs

**Comment by H0QLCoder** [comment]
Cool I don’t care that you got paid or work that company just so you know

**Comment by H0QLCoder** [comment]
You may leave

**Comment by VerstreuteSeele** [comment]
I appreciate that. Oh, by the way we have gone ahead and reported your paypal and linked them to this profile as distributing malware is totally against their ToS. 

Have a pleasant day

**Comment by omnituensaeternum** [comment]
Imagine being a skid @H0QLCoder

**Comment by H0QLCoder** [comment]
There is not malware in this nuker

**Comment by GalaxzyDev** [comment]
Oh, is that so?

**Comment by H0QLCoder** [comment]
Also show me
